version: '3'
services:
  web:
    build: ./docker/web
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ../ShareMovie/:/var/www/html/ShareMovie
  app:
    build: ./docker/php
    depends_on:
    - mysql
    volumes:
      - ../ShareMovie/:/var/www/html/ShareMovie
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: share_movie
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:80"
    volumes:
      - mysql-data:/path/to/data
volumes:
  mysql-data:
